import type { Metadata } from "next";
import { ReactNode } from "react";
import "tailwindcss/tailwind.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface AppLayoutProps {
  children?: ReactNode;
}

const AppLayout = ({ children }: AppLayoutProps) => (
  <html lang="en">
    <body>{children}</body>
  </html>
);

export default AppLayout;
